import type { Metadata } from 'next'
import Link from 'next/link'
import { Footer } from '@/components/footer'

export const metadata: Metadata = {
  title: "Child Safety & CSAE Standards | NGUMU'S EYE",
  description: "NGUMU'S EYE Child Safety Standards and policies against child sexual abuse and exploitation (CSAE) and child sexual abuse material (CSAM).",
  alternates: { canonical: 'https://web.ngumus-eye.site/child-safety' },
}

const sections = [
  {
    id: 'zero-tolerance',
    title: '1. Our Zero-Tolerance Policy',
    paragraphs: ["NGUMU’S EYE strictly prohibits the creation, upload, sharing, promotion, solicitation or distribution of content or behaviour involving the sexual abuse or exploitation of children."],
    bullets: ['Child Sexual Abuse Material (CSAM).', 'Sexual exploitation or sexual abuse of a child.', 'Grooming a child for sexual purposes.', 'Soliciting sexual content or sexual activity involving a child.', 'Sextortion involving a child.', 'Sexual trafficking or attempted trafficking of a child.', 'Encouraging or facilitating sexual contact with children.', 'Sharing, requesting or distributing sexual images or videos involving children.', 'Using NGUMU’S EYE to identify, contact or target children for sexual exploitation.', 'Content that promotes, normalises or facilitates child sexual abuse or exploitation.'],
    closing: 'This prohibition applies regardless of whether the content is posted publicly, submitted as part of an incident report, included in a comment, or uploaded as supporting information.',
  },
  { id: 'csam', title: '2. Child Sexual Abuse Material (CSAM)', paragraphs: ['NGUMU’S EYE does not permit CSAM on the platform.', 'Where NGUMU’S EYE becomes aware of suspected or confirmed CSAM, we may take immediate action including:'], bullets: ['Restricting access to the content.', 'Removing or disabling prohibited content where appropriate.', 'Suspending or terminating accounts involved in prohibited activity.', 'Preserving relevant information where required for lawful investigation or reporting.', 'Referring suspected illegal activity to appropriate law-enforcement, child-protection or other competent authorities where required by applicable law.'], closing: 'Users must never use NGUMU’S EYE to redistribute CSAM, even where their intention is to expose, report or condemn it. Where possible, users should report the incident without downloading, copying, forwarding or redistributing illegal material.' },
  { id: 'reporting', title: '3. Reporting Child Safety Concerns', paragraphs: ['Users may report child-safety concerns through the reporting and feedback mechanisms available within NGUMU’S EYE.', 'Reports may include concerns relating to:'], bullets: ['Suspected child abuse.', 'Child sexual exploitation.', 'Grooming.', 'Sextortion.', 'Child trafficking.', 'Inappropriate communication involving a child.', 'Suspected CSAM.', 'Other behaviour that may place a child at risk.'], closing: "Reports involving an immediate threat to a child's safety should also be reported directly to the appropriate emergency service, police or child-protection authority. NGUMU’S EYE should not be used as a substitute for emergency services." },
  { id: 'in-app-reporting', title: '4. In-App Reporting and Feedback', paragraphs: ['NGUMU’S EYE provides mechanisms that allow users to submit reports, information, concerns and supporting information from within the application.', 'Where a user encounters content or behaviour that may violate these Child Safety Standards, the user should use the available in-app reporting or feedback mechanism.', 'Reports received by NGUMU’S EYE may be reviewed and appropriate action taken based on the nature and severity of the concern.'] },
  { id: 'response', title: '5. How We Respond', paragraphs: ['When NGUMU’S EYE receives information indicating possible CSAE or CSAM, appropriate action may include:'], bullets: ['Reviewing the report.', 'Restricting access to reported content.', 'Escalating the matter for further review.', 'Removing content that violates these standards.', 'Restricting, suspending or terminating accounts.', 'Preserving relevant evidence where legally appropriate.', 'Cooperating with authorised law-enforcement or child-protection authorities.', 'Reporting confirmed illegal material or conduct to the appropriate authority where required by law.'], closing: 'The exact action taken will depend on the circumstances, available information and applicable legal requirements.' },
  { id: 'misuse', title: '6. Misuse of Incident Reporting', paragraphs: ['Because NGUMU’S EYE allows users to submit incident and case information, users must report responsibly. Users must not:'], bullets: ['Fabricate allegations involving children.', 'Upload exploitative material merely to attract attention to a report.', 'Publicly identify a child victim unnecessarily.', 'Reveal sensitive personal information about a child without lawful justification.', 'Harass, intimidate or retaliate against a child, victim, witness or person who makes a report.', 'Use NGUMU’S EYE to distribute material that could further exploit or endanger a child.'], closing: 'Information relating to children should be handled with particular care.' },
  { id: 'protection', title: '7. Protection of Children and Sensitive Information', paragraphs: ['Reports concerning children may contain highly sensitive personal information.', 'Users should submit only information that is reasonably necessary for reporting the incident or concern.', 'Users should avoid unnecessarily publishing identifying information about child victims, including sensitive photographs, addresses, school information or other information that could expose the child to further harm.', 'NGUMU’S EYE may restrict the visibility of information where necessary to protect users, victims or the integrity of an investigation.'] },
  { id: 'authorities', title: '8. Cooperation With Authorities', paragraphs: ['NGUMU’S EYE is committed to complying with applicable child-safety laws and lawful reporting obligations.', 'Where required, NGUMU’S EYE may cooperate with law-enforcement agencies, child-protection organisations or other competent authorities investigating suspected child abuse, exploitation, trafficking or related offences.', 'Confirmed CSAM or other conduct requiring mandatory reporting will be handled in accordance with applicable legal requirements and reported to the appropriate competent or regional authority where required.'] },
  { id: 'enforcement', title: '9. Account Enforcement', paragraphs: ['Users who violate these standards may have content removed or access to NGUMU’S EYE restricted or terminated.', 'Serious violations involving suspected criminal conduct may also be referred to relevant authorities.', 'Enforcement may include:'], bullets: ['Content removal.', 'Temporary account restriction.', 'Account suspension.', 'Permanent account termination.', 'Escalation to relevant authorities where appropriate.'] },
  { id: 'false-reports', title: '10. False or Malicious Reports', paragraphs: ['NGUMU’S EYE recognises the importance of allowing genuine child-safety concerns to be reported.', 'However, knowingly submitting false, fabricated or malicious allegations may itself violate NGUMU’S EYE policies and may result in account action.', 'A report will not be treated as malicious merely because an allegation cannot ultimately be confirmed. Good-faith reports are encouraged.'] },
  { id: 'immediate-danger', title: '11. Immediate Danger', paragraphs: ["If you believe a child is in immediate danger, contact your local police, emergency services or recognised child-protection authority immediately.", 'Do not rely solely on an NGUMU’S EYE report where urgent intervention is required.', 'In Namibia, suspected crimes against children should be reported to the appropriate authorities. Users may also seek assistance from recognised child-protection organisations.'] },
]

export default function ChildSafetyPage() {
  return <div className="min-h-screen bg-[#f7f9fc] text-[#101b33]">
    <header className="bg-[#eaf5ff] px-5 py-6 sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><Link href="/" className="flex items-center gap-3" aria-label="Ngumu's Eye home"><img src="/ngumus-eye-logo.png" alt="Ngumu's Eye logo" className="size-10 object-contain" /><span className="font-heading text-lg font-bold">NGUMU&apos;S EYE</span></Link><Link href="/" className="inline-flex shrink-0 items-center gap-2 rounded-lg border border-[#c7d5e5] bg-white px-4 py-2 text-sm font-semibold text-[#10234a] hover:border-[#078fe8]">Back home</Link></div></header>
    <main className="px-5 py-12 sm:px-8 sm:py-16"><article className="mx-auto max-w-3xl rounded-2xl border border-[#dce7f2] bg-white p-6 shadow-sm sm:p-10"><div className="mb-10 border-b border-[#e5edf5] pb-8"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#078fe8]">Safety &amp; Community Standards</p><h1 className="mt-4 font-heading text-3xl font-extrabold leading-tight text-[#10234a] sm:text-4xl">NGUMU&apos;S EYE Child Safety &amp; CSAE Standards</h1><p className="mt-3 text-sm text-[#60708a]">Last updated: September 2026</p><p className="mt-6 text-base leading-7 text-[#60708a]">NGUMU&apos;S EYE is committed to maintaining a safe platform and protecting children from sexual abuse, exploitation and other forms of harm.</p><p className="mt-4 font-semibold leading-7 text-[#10234a]">We have a zero-tolerance policy for Child Sexual Abuse and Exploitation (CSAE) and Child Sexual Abuse Material (CSAM).</p><p className="mt-4 leading-7 text-[#60708a]">These standards apply to all users, reports, comments, documents, images, videos, attachments and other content submitted through NGUMU&apos;S EYE.</p></div>
      <nav aria-label="On this page" className="mb-10 rounded-xl bg-[#f4f8fc] p-5"><h2 className="font-heading text-sm font-bold text-[#10234a]">On this page</h2><ul className="mt-3 grid gap-2 text-sm text-[#078fe8] sm:grid-cols-2">{sections.map((section) => <li key={section.id}><a className="underline-offset-4 hover:underline" href={`#${section.id}`}>{section.title}</a></li>)}<li><a className="underline-offset-4 hover:underline" href="#contact">12. Child Safety Point of Contact</a></li></ul></nav>
      <div className="flex flex-col gap-9 text-sm leading-7 text-[#60708a]">{sections.map((section) => <section id={section.id} key={section.id} className="scroll-mt-6"><h2 className="font-heading text-xl font-bold leading-snug text-[#10234a]">{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-3">{paragraph}</p>)}{section.bullets && <ul className="mt-3 list-disc space-y-2 pl-5">{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}{section.closing && <p className="mt-3">{section.closing}</p>}</section>)}
        <section id="contact" className="scroll-mt-6"><h2 className="font-heading text-xl font-bold leading-snug text-[#10234a]">12. Child Safety Point of Contact</h2><p className="mt-3">NGUMU’S EYE maintains a designated contact for child-safety matters, including communications concerning CSAE and CSAM.</p><div className="mt-4 rounded-xl border border-[#dce7f2] bg-[#f8fbfe] p-5"><p className="font-semibold text-[#10234a]">Child Safety Contact</p><p>NGUMU&apos;S EYE</p><p>Email: <a href="mailto:ngumuseye@gmail.com" className="font-semibold text-[#078fe8] underline">ngumuseye@gmail.com</a></p></div><p className="mt-4">This contact may be used by users, Google Play, law-enforcement agencies and recognised child-protection authorities for matters concerning child safety, CSAE or CSAM on NGUMU’S EYE.</p><p className="mt-3">Please do not email or attach suspected CSAM. Instead, provide sufficient information for us to identify and investigate the relevant report or content safely.</p></section>
        <section id="changes" className="scroll-mt-6"><h2 className="font-heading text-xl font-bold leading-snug text-[#10234a]">13. Changes to These Standards</h2><p className="mt-3">NGUMU’S EYE may update these Child Safety &amp; CSAE Standards as our services, safety procedures or legal obligations evolve.</p><p className="mt-3">The latest version will remain publicly available on the official NGUMU’S EYE website.</p></section>
      </div><div className="mt-10 border-t border-[#e5edf5] pt-6 text-sm font-semibold text-[#10234a]"><p>NGUMU&apos;S EYE</p><p className="mt-1 text-[#60708a]">Community safety through responsible reporting.</p><p className="mt-1 text-[#60708a]">Zero tolerance for child sexual abuse and exploitation.</p></div>
    </article></main><Footer />
  </div>
}

export const dynamic = 'force-static'
export const revalidate = false

// The support address above is the existing public support contact configured in the site footer.
// Replace it here if a dedicated child-safety mailbox is introduced.
