"use client"

import Image from "next/image"

const apkUrl = "https://drive.google.com/uc?export=download&id=1cK-cC08sefHyg8wpGwLy1bMcUs6A8Pko"

const screens = [
  { image: "/phone-feed.png", title: "Stay close to what matters", text: "A community feed that turns local updates into useful, trusted awareness." },
  { image: "/phone-filedeck.png", title: "Keep every case organised", text: "Reports, counselling, device tracking, and follow-ups live in one clear file deck." },
  { image: "/phone-report.png", title: "Report with the right context", text: "A guided incident flow helps you capture the details people need to respond." },
]

const benefits = [
  ["01", "See what is happening", "Follow relevant updates without the noise. Find verified, nearby information in one place."],
  ["02", "Build community trust", "Transparent trust signals help people understand who is sharing information and why it matters."],
  ["03", "Support your family", "Choose a plan, manage access, and keep the people closest to you connected."],
]

export function LandingPage() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#f7f9fc] text-[#101b33]">
      <header className="absolute inset-x-0 top-0 z-30">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10">
          <a href="#top" className="flex items-center gap-3" aria-label="Ngumu's Eye home"><span className="grid size-10 place-items-center rounded-xl bg-[#10234a] text-xs font-black text-white">NE</span><span className="font-heading text-lg font-bold tracking-tight">Ngumu&apos;s Eye</span></a>
          <nav className="hidden items-center gap-8 text-sm font-semibold text-[#60708a] md:flex"><a href="#platform" className="hover:text-[#078fe8]">Platform</a><a href="#plans" className="hover:text-[#078fe8]">Membership</a><a href="#download" className="hover:text-[#078fe8]">Download</a></nav>
          <a href={apkUrl} target="_blank" rel="noreferrer" className="rounded-full bg-[#078fe8] px-5 py-2.5 text-sm font-bold text-white shadow-lg shadow-[#078fe8]/20 hover:bg-[#0577c5]">Get the APK</a>
        </div>
      </header>

      <section id="top" className="relative bg-[#eaf5ff] pt-32 lg:pt-40"><div className="absolute -right-40 top-0 size-[34rem] rounded-full bg-[#d8edff] blur-3xl" /><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 pb-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:pb-28"><div className="relative z-10 max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#b9dcf6] bg-white/70 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-[#078fe8]"><span className="size-2 rounded-full bg-[#f2aa35]" /> Community safety, made actionable</div><h1 className="font-heading text-5xl font-extrabold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-8xl">Look out for <span className="text-[#078fe8]">your people.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#60708a]">Ngumu&apos;s Eye brings reporting, community awareness, trust, and family support into one calm, practical mobile experience.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href={apkUrl} target="_blank" rel="noreferrer" className="inline-flex justify-center rounded-xl bg-[#078fe8] px-7 py-4 font-bold text-white shadow-xl shadow-[#078fe8]/25 hover:-translate-y-0.5 hover:bg-[#0577c5]">Download the Android APK <span className="ml-2">↗</span></a><a href="#platform" className="inline-flex justify-center rounded-xl border border-[#c7d5e5] bg-white px-7 py-4 font-bold hover:border-[#078fe8] hover:text-[#078fe8]">See how it works</a></div><div className="mt-6 flex flex-wrap gap-3"><div className="inline-flex items-center gap-3 rounded-xl border border-[#cbd8e7] bg-white px-4 py-3 shadow-sm"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/google-play/default.svg" alt="Google Play" className="size-6" /><div><p className="text-xs font-bold text-[#101b33]">Google Play</p><p className="text-[11px] font-semibold text-[#078fe8]">Coming soon</p></div></div><div className="inline-flex items-center gap-3 rounded-xl border border-[#cbd8e7] bg-white px-4 py-3 shadow-sm"><img src="https://thesvg.org/icons/apple/default.svg" alt="Apple App Store" className="size-6" /><div><p className="text-xs font-bold text-[#101b33]">App Store</p><p className="text-[11px] font-semibold text-[#078fe8]">Coming soon</p></div></div></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm font-semibold text-[#708097]"><span>Android 8.0+</span><span>Free to download</span><span>Made for Namibia</span></div></div><div className="relative flex justify-center lg:justify-end"><div className="absolute bottom-8 h-20 w-72 rounded-full bg-[#078fe8]/20 blur-3xl" /><Image src="/phone-feed.png" alt="Ngumu's Eye community feed screen" width={444} height={700} priority className="relative w-[290px] drop-shadow-[0_35px_40px_rgba(16,35,74,.25)] sm:w-[350px] lg:w-[405px]" /></div></div></section>

      <section id="platform" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#078fe8]">One platform, many ways to help</p><h2 className="mt-4 font-heading text-4xl font-extrabold leading-tight tracking-[-.045em] sm:text-6xl">From first alert to follow-through.</h2></div><p className="max-w-xl text-lg leading-8 text-[#60708a]">Every screen has a job: make it easier to notice, report, organise, and support what matters in your community.</p></div><div className="mt-14 grid gap-16 lg:grid-cols-3">{screens.map((screen, index) => <article key={screen.image} className={`flex flex-col ${index === 1 ? "lg:mt-20" : ""}`}><div className="flex min-h-[480px] items-end justify-center rounded-[2rem] bg-[#edf5fb] px-5 pt-8"><Image src={screen.image} alt={screen.title} width={444} height={700} className="w-[245px] drop-shadow-[0_20px_28px_rgba(16,35,74,.2)]" /></div><p className="mt-7 text-sm font-bold text-[#078fe8]">0{index + 1}</p><h3 className="mt-2 font-heading text-2xl font-bold">{screen.title}</h3><p className="mt-3 leading-7 text-[#60708a]">{screen.text}</p></article>)}</div></section>

      <section className="bg-[#10234a] text-white"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1.15fr_.85fr] lg:px-10 lg:py-28"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#6fc9ff]">Designed for real life</p><h2 className="mt-4 max-w-2xl font-heading text-4xl font-extrabold leading-tight tracking-[-.045em] sm:text-6xl">Clarity when the moment calls for it.</h2><div className="mt-10 grid gap-7 sm:grid-cols-3">{benefits.map(([number, title, text]) => <div key={number}><p className="text-sm font-bold text-[#f3ae3c]">{number}</p><h3 className="mt-3 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#b9c9df]">{text}</p></div>)}</div></div><div className="flex justify-center lg:justify-end"><Image src="/phone-report.png" alt="Ngumu's Eye guided incident report screen" width={444} height={700} className="w-[285px] drop-shadow-2xl" /></div></div></section>

      <section id="plans" className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:px-10 lg:py-28"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#078fe8]">Membership that fits</p><h2 className="mt-4 font-heading text-4xl font-extrabold leading-tight tracking-[-.045em] sm:text-6xl">More support for more of your people.</h2><p className="mt-6 max-w-lg text-lg leading-8 text-[#60708a]">Choose a membership plan that fits your household. Plans are paid locally through PaySME, making activation simple and familiar.</p><a href={apkUrl} target="_blank" rel="noreferrer" className="mt-8 inline-flex rounded-xl bg-[#10234a] px-6 py-3.5 font-bold text-white hover:bg-[#1c3b73]">Explore membership in the app</a></div><div className="flex justify-center gap-[-1rem] lg:justify-end"><Image src="/phone-membership-new.png" alt="Ngumu's Eye membership packages screen" width={444} height={700} className="relative z-10 w-[245px] drop-shadow-2xl" /><Image src="/phone-payment.png" alt="Ngumu's Eye payment request screen" width={444} height={700} className="-ml-16 mt-20 hidden w-[220px] drop-shadow-2xl sm:block" /></div></section>

      <footer className="bg-[#071021] px-5 py-10 text-sm text-[#9eabc0] sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><p className="font-semibold text-white">Ngumu&apos;s Eye</p><div className="flex flex-wrap gap-5"><a href="/privacy-policy" className="hover:text-white">Privacy Policy</a><a href="/terms-of-service" className="hover:text-white">Terms of Service</a><a href="#plans" className="hover:text-white">Membership</a><a href="/request-account-removal" className="hover:text-white">Request Account Removal</a></div><p>© 2026 Ngumu&apos;s Eye</p></div></footer>
    </main>
  )
}
